CREATE TABLE contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying NOT NULL,
  phone_number character varying,
  tags text[] DEFAULT '{}',
  matter_id bigint REFERENCES workspaces(id) NOT NULL,
  created_by uuid REFERENCES auth.users(id) NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  archived boolean DEFAULT false NOT NULL,
  archived_by uuid REFERENCES auth.users(id) NULL,
  archived_at timestamp with time zone NULL,
  
  CONSTRAINT archive_consistency CHECK (
    (archived = false AND archived_by IS NULL AND archived_at IS NULL) OR
    (archived = true AND archived_by IS NOT NULL AND archived_at IS NOT NULL)
  )
);

COMMENT ON TABLE contacts IS 'Contacts associated with workspaces/workspaces.
Each contact belongs to a specific matter and can have:
1. Name (required)
2. Phone number (optional)
3. Tags (array of text tags for categorization)
4. Standard audit fields (created_by, created_at, updated_at)
5. Soft delete capability (archived, archived_by, archived_at)';

-- Indexes for contacts
CREATE INDEX contacts_matter_id_idx ON public.contacts USING btree (matter_id);
CREATE INDEX contacts_created_by_idx ON public.contacts USING btree (created_by);
CREATE INDEX contacts_archived_idx ON public.contacts USING btree (archived);
CREATE INDEX contacts_archived_by_idx ON public.contacts USING btree (archived_by);

-- RLS for contacts
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Policies for contacts
CREATE POLICY "Users can view contacts" ON contacts
FOR SELECT USING (
  matter_id IN (
    SELECT matter_id 
    FROM workspace_access 
    WHERE shared_with_user_id = auth.uid()
  )
);

CREATE POLICY "Users can update contacts" ON contacts
FOR UPDATE USING (
  matter_id IN (
    SELECT matter_id 
    FROM workspace_access 
    WHERE shared_with_user_id = auth.uid() 
    AND access_type = 'edit'
  )
);

CREATE POLICY "Users can create contacts" ON contacts
FOR INSERT WITH CHECK (
  matter_id IN (
    SELECT matter_id 
    FROM workspace_access 
    WHERE shared_with_user_id = auth.uid() 
    AND access_type = 'edit'
  )
);

CREATE POLICY "Users can archive contacts" ON contacts
FOR UPDATE USING (
  matter_id IN (
    SELECT matter_id 
    FROM workspace_access 
    WHERE shared_with_user_id = auth.uid() 
    AND access_type = 'edit'
  )
); 