    CREATE TABLE goals (
      created_at timestamp with time zone DEFAULT now() NOT NULL,
      updated_at timestamp with time zone DEFAULT now() NOT NULL,
      created_by uuid,
      related_files jsonb,
      matter_id bigint,
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      title character varying NOT NULL,
      description text,
      status character varying,
      priority character varying,
      due_date timestamp with time zone
    );
    
    -- Indexes for goals
    CREATE INDEX goals_created_by_idx ON public.goals USING btree (created_by);
    CREATE INDEX goals_status_idx ON public.goals USING btree (status); 
    CREATE INDEX goals_due_date_idx ON public.goals USING btree (due_date);
    CREATE INDEX goals_matter_id_idx ON public.goals USING btree (matter_id);
    
    -- RLS for goals
    ALTER TABLE goals ENABLE ROW LEVEL SECURITY;
    
    -- Policies for goals
    CREATE POLICY "Users can view goals" ON goals
    FOR SELECT USING (
      matter_id IN (
        SELECT id FROM matters WHERE created_by = auth.uid()
        UNION
        SELECT matter_id FROM matter_shares WHERE shared_with_user_id = auth.uid()
      )
    );

    CREATE POLICY "Users can update goals" ON goals
    FOR UPDATE USING (
      matter_id IN (
        SELECT id FROM matters WHERE created_by = auth.uid()
        UNION
        SELECT matter_id FROM matter_shares 
        WHERE shared_with_user_id = auth.uid() AND access_type = 'edit'
      )
    );

    CREATE POLICY "Users can delete goals" ON goals
    FOR DELETE USING (
      matter_id IN (
        SELECT id FROM matters WHERE created_by = auth.uid()
        UNION
        SELECT matter_id FROM matter_shares 
        WHERE shared_with_user_id = auth.uid() AND access_type = 'edit'
      )
    );

    CREATE POLICY "Users can create goals" ON goals
    FOR INSERT WITH CHECK (
      matter_id IN (
        SELECT id FROM matters WHERE created_by = auth.uid()
        UNION
        SELECT matter_id FROM matter_shares 
        WHERE shared_with_user_id = auth.uid() AND access_type = 'edit'
      )
    );
    
