CREATE TABLE matters (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying NOT NULL,
    description text,
    created_by uuid REFERENCES auth.users(id),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Create indexes
CREATE INDEX matters_created_by_idx ON matters USING btree (created_by);

-- Enable Row Level Security
ALTER TABLE matters ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies
CREATE POLICY "Users can create matters" 
    ON matters FOR INSERT 
    WITH CHECK (auth.uid() = created_by);

CREATE POLICY "Users can view their own matters" 
    ON matters FOR SELECT 
    USING (auth.uid() = created_by);

CREATE POLICY "Users can update their own matters" 
    ON matters FOR UPDATE 
    USING (auth.uid() = created_by);

CREATE POLICY "Users can delete their own matters" 
    ON matters FOR DELETE 
    USING (auth.uid() = created_by);
