CREATE TABLE matter_shares (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matter_id bigint REFERENCES matters(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    access_type varchar NOT NULL CHECK (access_type IN ('view', 'edit')),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(matter_id, user_id)
);

-- Create indexes
CREATE INDEX matter_shares_matter_id_idx ON matter_shares(matter_id);
CREATE INDEX matter_shares_user_id_idx ON matter_shares(user_id);

-- Enable RLS
ALTER TABLE matter_shares ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Users can view shares for their matters"
    ON matter_shares FOR SELECT
    USING (
        matter_id IN (
            SELECT id FROM matters WHERE created_by = auth.uid()
        )
        OR
        user_id = auth.uid()
    );

CREATE POLICY "Matter owners can manage shares"
    ON matter_shares FOR ALL
    USING (
        matter_id IN (
            SELECT id FROM matters WHERE created_by = auth.uid()
        )
    ); 